[package]
name = "squint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bonsaidb = "0.4.1"
chrono = "0.4.24"
dateparser = "0.2.0"
eyre = "0.6.8"
rss = "2.0.3"
url = "2.3.1"
